from python_app.test.models.audio_app import AudioApp

def appDebug(apps: list[AudioApp]) -> None:
    """
    Prints debug information for all AudioApp objects.

    Args:
        apps:
            Application list to display.
    """
    for app in apps:
        
        print(app.friendlyName, app.audioSessionPIDs, app.topProcessPID, len(app.sessions), app.execPath)

def printDebugMessage(apps: list[AudioApp], index: int, msg: str | None) -> None:
    """
    Processes and displays debug messages generated by the application.

    Args:
        apps:
            Current application list.

        index:
            Index of the currently selected application.

        msg:
            Debug message to display.
    """

    if msg is None:

        return
    
    elif msg == "update":

        appDebug(apps)

    elif msg == "master":

        print("long press master")

    elif msg == "appUP":

        print(apps[index])
        
    elif msg == "appDWN":

        print(apps[index])

    else:

        print(msg)